# Copyright 2010 Digital Aggregates Corporation, Arvada CO 80001-0587 USA
# Licensed under the terms in README.h
# Chip Overclock <coverclock@diag.com>
# http://www.diag.com/navigation/downloads/Diminuto.html

obj-m := diminuto_utmodule.o diminuto_mmdriver.o
EXTRA_CFLAGS := -I$(shell cd /home/jsloan/src/Diminuto; pwd)
