/* vi: set ts=4 expandtab shiftwidth=4: */
#ifndef _H_COM_DIAG_DIMINUTO_LOG_ERROR_
#define _H_COM_DIAG_DIMINUTO_LOG_ERROR_

/**
 * @file
 * @copyright Copyright 2009-2022 Digital Aggregates Corporation, Colorado, USA.
 * @note Licensed under the terms in LICENSE.txt.
 * @brief Implements a logging version of perror(3).
 * @author Chip Overclock <mailto:coverclock@diag.com>
 * @see Diminuto <https://github.com/coverclock/com-diag-diminuto>
 * @details
 *
 * This provides a version of perror(3) that uses the Diminuto logging
 * system. These functions are part of the Log feature, and can be used
 * by just including the Log feature header. However, they can also be
 * used by themselves by just including this header.
 */

#include <errno.h>

/**
 * Emulate perror() but instead of writing the prefixed error string to
 * standard error, log it to the system log.
 * @param file is the nul-terminated string  generated by __FILE__.
 * @param line is the integer generated by __LINE__.
 * @param string points to a nul-terminated string prepended to the error string.
 * @see perror(3).
 */
extern void diminuto_log_serror(const char * file, int line, const char * string);

/**
 * @def diminuto_serror
 * Calls diminuto_serror_f with __FILE__, __LINE__, and @a _STRING_.
 */
#define diminuto_serror(_STRING_) diminuto_log_serror(__FILE__, __LINE__, _STRING_)

/**
 * If the calling process is interactive, emulate the stdio
 * function perror(); if it is, still emulate perror() but instead of writing
 * the prefixed error string to standard error, log it to the system log.
 * @param file is the nul-terminated string  generated by __FILE__.
 * @param line is the integer generated by __LINE__.
 * @param string points to a nul-terminated string prepended to the error string.
 * @see perror(3).
 */
extern void diminuto_log_perror(const char * file, int line, const char * string);

/**
 * @def diminuto_perror
 * Calls diminuto_perror_f with __FILE__, __LINE__, and @a _STRING_.
 */
#define diminuto_perror(_STRING_) diminuto_log_perror(__FILE__, __LINE__, _STRING_)

#if defined(COM_DIAG_DIMINUTO_DEPRECATED)
#   warning This code is deprecated!
#   define diminuto_serror_f diminuto_log_serror
#   define diminuto_perror_f diminuto_log_perror
#endif

#endif
